[project]
name = "joe"
version = "0.1.0"
description = "Audio Workbench - inspired by and named after Joeseph Fourier"
authors = [
    {name = "Peter Kagstrom", email = "peter.kagstrom@gmail.com"},
]
dependencies = [
    "librosa",
    "matplotlib",
    "music21",
    "pytest",
    "pytest-sugar",
    "nox",
    "numpy",
    "spacy",
    "whisper-openai",
    "sounddevice",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
